name: trigger cf deployment

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_PAGES_API_TOKEN }}
          accountId: b0dda00db555f237f277259bed93134b
          packageManager: bun
          command: pages deploy public --project-name=feed-tianheg --commit-dirty=true
