name: Trigger Vercel build

on:
  workflow_dispatch:
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    run: curl -X POST ${{ secrets.VERCEL_HOOK }}
