name: Update README and feed.opml

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'feeds.csv'
      - 'formatter.py'
      - 'opml_generator.py'
      - 'script.js'
      - '.github/workflows/update.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: formatter
        run: |
          python formatter.py
      - name: update readme
        run: |
          yarn install
          node script.js
      - name: Generate feed.opml
        run: |
          python opml_generator.py
      - name: Commit changes
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "update README and feed.opml after adding feed(s)" || true
      - name: Push changes
        uses: tianheg/github-actions@push
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
