name: Update readme and feed.opml

on:
  workflow_dispatch:
  push:
    paths: 
      - 'feeds.csv'
      - 'formatter.py'
      - 'opml_generator.py'
      - 'script.js'
      - '.github/workflows/update.yaml'
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: formatter
        run: |
          python formatter.py
      - name: update readme
      run: |
        npm install
        node script.js
    - name: Generate feed.opml
      run: |
        python opml_generator.py
    - name: update readme
      run: |
        npm install
        node script.js
    - name: Generate feed.opml
      run: |
        python opml_generator.py
    - name: Generate feed.opml
        run: |
          python opml_generator.py
    - name: Commit change & Push
        run: |
          git diff
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "bot: update README.md automatically"
          git push