name: Build RSS site

on:
  push:
    paths: 
      - 'feeds.csv'
      - 'formatter.py'
      - 'opml_generator.py'
      - 'script.js'
      - '.github/workflows/update-feed.yaml'
    branches:
      - main
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "14"
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: formatter
        run: |
          python formatter.py
      - name: Install dependencies
        run: yarn install
      - name: update readme
        run: |
          node script.js
      - name: Generate feed.opml
        run: |
          python opml_generator.py
      - name: Commit change & Push
        run: |
          git diff
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "bot: update README.md automatically"
          git push
      - name: Build the feed
        run: yarn run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          CNAME: feed.yidajiabei.xyz